.PHONY: clean All

All:
	@echo "----------Building project:[ Assignment2Codelite - Debug ]----------"
	@cd "Assignment2Codelite" && "$(MAKE)" -f  "Assignment2Codelite.mk"
clean:
	@echo "----------Cleaning project:[ Assignment2Codelite - Debug ]----------"
	@cd "Assignment2Codelite" && "$(MAKE)" -f  "Assignment2Codelite.mk" clean
